### ISSUE TITLE
新增实例：统一社会信用代码

### ISSUE THREAD

**Issue by ntnyq** [jaywcjlove/regexp-example#23]
正则:

`/[1-9ANY][1-59]\d{6}[\dA-Z]{8}[\dX][\dA-HJ-NP-RTUW-Y]/`

标准: 

- [GB 32100-2015 法人和其他组织统一社会信用代码编码规则](https://zh.wikisource.org/wiki/GB_32100-2015_%E6%B3%95%E4%BA%BA%E5%92%8C%E5%85%B6%E4%BB%96%E7%BB%84%E7%BB%87%E7%BB%9F%E4%B8%80%E7%A4%BE%E4%BC%9A%E4%BF%A1%E7%94%A8%E4%BB%A3%E7%A0%81%E7%BC%96%E7%A0%81%E8%A7%84%E5%88%99)
- [国务院关于批转发展改革委等部门法人和其他组织统一社会信用代码制度建设总体方案的通知 - 国发〔2015〕33 号](http://www.gov.cn/zhengce/content/2015-06/17/content_9858.htm)

维基上有个更严格的正则 `/[1-9ANY][123459](100000|110000|11010[1-9]|1101[1-9]\d|110[2-9]\d{2}|11[1-9]\d{3}|[2-5]\d{5}|6[0-4]\d{4}|65[0-8]\d{3}|6590\d{2}|990000)[0-9A-Z]{8}[0-9X][0-9A-Y]/` 但实际发现 `92141127MA0KD1Y64A` 无法通过，这条数据可以在 [全国组织机构统一社会信用代码数据服务中心](https://www.cods.org.cn/) 查询到。

**Comment by jaywcjlove** [comment]
@ntnyq 已添加谢谢
