### ISSUE TITLE
小数点后几位  通常 0000是不合法的

### ISSUE THREAD

**Issue by cuilanxin** [jaywcjlove/regexp-example#3]
<img width="1032" alt="WX20211125-160244@2x" src="https://user-images.githubusercontent.com/57083007/143402722-f5a9535c-1994-49ac-a1e8-8773936bac2a.png">
我尝试这样写  /^(0|[1-9]\d*)(\.\d{n,m})?$/ 是可行的

**Comment by jaywcjlove** [comment]
@cuilanxin 你要表示 `00.1`, `0.`  不合法？

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/143415741-2a6fd849-587b-430f-a4ac-25fa15c7b15b.png)

**Comment by jaywcjlove** [comment]
#4

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/143416968-3624f133-7ff4-4bf5-8b1d-73d8983f8e08.png)

在JS中合法的 :)
